"""phase3 database connections schema tables columns

Revision ID: 8d30e5156554
Revises: c7a9e5a73d90
Create Date: 2026-08-02 17:26:21.372732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8d30e5156554'
down_revision: Union[str, None] = 'c7a9e5a73d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('database_type', sa.String(length=50), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('database_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('encrypted_password', sa.Text(), nullable=True),
    sa.Column('encrypted_connection_string', sa.Text(), nullable=True),
    sa.Column('ssl_enabled', sa.Boolean(), nullable=False),
    sa.Column('ssl_settings', sa.JSON(), nullable=False),
    sa.Column('connection_options', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_message', sa.Text(), nullable=True),
    sa.Column('schema_sync_status', sa.String(length=30), nullable=False),
    sa.Column('last_schema_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_database_connection_name')
    )
    op.create_index(op.f('ix_database_connections_tenant_id'), 'database_connections', ['tenant_id'], unique=False)
    op.create_table('database_schemas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('schema_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'schema_name', name='uq_database_schema')
    )
    op.create_index(op.f('ix_database_schemas_connection_id'), 'database_schemas', ['connection_id'], unique=False)
    op.create_index(op.f('ix_database_schemas_tenant_id'), 'database_schemas', ['tenant_id'], unique=False)
    op.create_table('database_tables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('schema_id', sa.Uuid(), nullable=True),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('table_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_row_count', sa.BigInteger(), nullable=True),
    sa.Column('primary_key_columns', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schema_id'], ['database_schemas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'schema_id', 'table_name', name='uq_database_table')
    )
    op.create_index(op.f('ix_database_tables_connection_id'), 'database_tables', ['connection_id'], unique=False)
    op.create_index(op.f('ix_database_tables_tenant_id'), 'database_tables', ['tenant_id'], unique=False)
    op.create_table('database_columns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('table_id', sa.Uuid(), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=100), nullable=False),
    sa.Column('ordinal_position', sa.Integer(), nullable=True),
    sa.Column('is_nullable', sa.Boolean(), nullable=True),
    sa.Column('is_primary_key', sa.Boolean(), nullable=False),
    sa.Column('is_foreign_key', sa.Boolean(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('referenced_schema', sa.String(length=255), nullable=True),
    sa.Column('referenced_table', sa.String(length=255), nullable=True),
    sa.Column('referenced_column', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sample_values', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['database_tables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'column_name', name='uq_database_column')
    )
    op.create_index(op.f('ix_database_columns_table_id'), 'database_columns', ['table_id'], unique=False)
    op.create_index(op.f('ix_database_columns_tenant_id'), 'database_columns', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_database_columns_tenant_id'), table_name='database_columns')
    op.drop_index(op.f('ix_database_columns_table_id'), table_name='database_columns')
    op.drop_table('database_columns')
    op.drop_index(op.f('ix_database_tables_tenant_id'), table_name='database_tables')
    op.drop_index(op.f('ix_database_tables_connection_id'), table_name='database_tables')
    op.drop_table('database_tables')
    op.drop_index(op.f('ix_database_schemas_tenant_id'), table_name='database_schemas')
    op.drop_index(op.f('ix_database_schemas_connection_id'), table_name='database_schemas')
    op.drop_table('database_schemas')
    op.drop_index(op.f('ix_database_connections_tenant_id'), table_name='database_connections')
    op.drop_table('database_connections')
    # ### end Alembic commands ###
