"""phase4 table column permissions query executions

Revision ID: abd12906673b
Revises: 8d30e5156554
Create Date: 2026-08-02 17:54:45.691663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'abd12906673b'
down_revision: Union[str, None] = '8d30e5156554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('generated_sql', sa.Text(), nullable=False),
    sa.Column('normalized_sql', sa.Text(), nullable=True),
    sa.Column('query_type', sa.String(length=30), nullable=True),
    sa.Column('validation_status', sa.String(length=30), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=False),
    sa.Column('applied_row_filters', sa.JSON(), nullable=False),
    sa.Column('referenced_tables', sa.JSON(), nullable=False),
    sa.Column('referenced_columns', sa.JSON(), nullable=False),
    sa.Column('execution_status', sa.String(length=30), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('returned_row_count', sa.Integer(), nullable=True),
    sa.Column('result_preview', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_executions_connection_id'), 'query_executions', ['connection_id'], unique=False)
    op.create_index(op.f('ix_query_executions_conversation_id'), 'query_executions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_query_executions_message_id'), 'query_executions', ['message_id'], unique=False)
    op.create_index(op.f('ix_query_executions_tenant_id'), 'query_executions', ['tenant_id'], unique=False)
    op.create_table('table_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('table_id', sa.Uuid(), nullable=False),
    sa.Column('can_read', sa.Boolean(), nullable=False),
    sa.Column('can_insert', sa.Boolean(), nullable=False),
    sa.Column('can_update', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.Column('row_filter', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(role_id IS NOT NULL AND user_id IS NULL) OR (role_id IS NULL AND user_id IS NOT NULL)', name='chk_permission_subject'),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['database_tables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_permissions_connection_id'), 'table_permissions', ['connection_id'], unique=False)
    op.create_index(op.f('ix_table_permissions_table_id'), 'table_permissions', ['table_id'], unique=False)
    op.create_index(op.f('ix_table_permissions_tenant_id'), 'table_permissions', ['tenant_id'], unique=False)
    op.create_table('column_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('table_permission_id', sa.Uuid(), nullable=False),
    sa.Column('column_id', sa.Uuid(), nullable=False),
    sa.Column('can_read', sa.Boolean(), nullable=False),
    sa.Column('can_filter', sa.Boolean(), nullable=False),
    sa.Column('can_aggregate', sa.Boolean(), nullable=False),
    sa.Column('mask_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['database_columns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_permission_id'], ['table_permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_permission_id', 'column_id', name='uq_column_permission')
    )
    op.create_index(op.f('ix_column_permissions_column_id'), 'column_permissions', ['column_id'], unique=False)
    op.create_index(op.f('ix_column_permissions_table_permission_id'), 'column_permissions', ['table_permission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_column_permissions_table_permission_id'), table_name='column_permissions')
    op.drop_index(op.f('ix_column_permissions_column_id'), table_name='column_permissions')
    op.drop_table('column_permissions')
    op.drop_index(op.f('ix_table_permissions_tenant_id'), table_name='table_permissions')
    op.drop_index(op.f('ix_table_permissions_table_id'), table_name='table_permissions')
    op.drop_index(op.f('ix_table_permissions_connection_id'), table_name='table_permissions')
    op.drop_table('table_permissions')
    op.drop_index(op.f('ix_query_executions_tenant_id'), table_name='query_executions')
    op.drop_index(op.f('ix_query_executions_message_id'), table_name='query_executions')
    op.drop_index(op.f('ix_query_executions_conversation_id'), table_name='query_executions')
    op.drop_index(op.f('ix_query_executions_connection_id'), table_name='query_executions')
    op.drop_table('query_executions')
    # ### end Alembic commands ###
